### ISSUE TITLE
Clearer analysis of cache key situation

### ISSUE THREAD

**Issue by guybedford** [tc39/proposal-import-reflection#1]
This proposal will need to more clearly tackle the cache key questions head on.

Specifically some of the details around:
* HTML already does double-keying for import assertions in that an assert and non assert for the same module can race I believe (cc @bmeck if I've got this wrong)
* How this affects the idempotency requirement of host resolve imported module, and how it would be adjusted.
* If the evaluator attribute would be permitted to alter resolution itself (eg changing the resolved URL).

**Comment by lucacasonato** [comment]
Guy and me discussed this in private. Here is my take:

- Split "asset load" and "evaluate" into two separate host functions, each being idempotent.
  - "asset load" takes a referencingScriptOrModule and a specifier, returning an "asset" (opaque, value up to host environment)
  - "evaluate" takes an "asset" and evaluator attribute and returns a Module Record

This would have the following effects:
- Evaluator attributes can not affect specifier resolving
- Evaluator attributes can not result in multiple "loads" (HTTP fetches, disk loads etc).

**Comment by guybedford** [comment]
Thanks for the summary here @lucacasonato, that sounds very clear to me and a really elegant separation of concerns.

To try rephrase in ECMA-262 terms:

* `HostResolveImportedModule` is split up into two separate host functions that are composed together - `HostResolveImportedModuleAsset` and `HostResolveModuleInstance` (names as placeholders entirely for now)
* `HostResolveImportedModuleAsset` is a function of `specifier` and `referencingScriptOrModule`, and is idempotent on that input.
* `HostResolveModuleInstance` is a function of `ModuleAsset` and `Type`, and fully idempotent on that input.
* This decomposition is fully backwards compatible since `HostResolveModuleInstance` o HostResolveImportedModuleAsset` is idempotent on `specifier` and `referencingScriptOrModule` as before.
* Import assertion failures are handled in `HostResolveModuleInstance`.

My only concern with the term "asset" is that these feels like it separates JS from other formats, when we should maybe think of the opaque type working for both. We could even be more direct and call it `ModuleCacheKey`.

**Comment by guybedford** [comment]
Sorry, on second thoughts I think `"asset"` is actually exactly the right terms since that does seem to adequately capture a file or network asset, as long as we are clear this applies to all modules.

We are effectively describing two registries here (the asset registry, and the instance registry), so it makes no sense to refer to a single key at this point.
