### ISSUE TITLE
Parameterized Evaluators

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-import-reflection#13]
Much like import assertions is a generic mechanism. I could imagine non-WASM evaluators and parameterization of them:

```mjs
import './model.json' assert { 
  type: 'json'
} as {
  evaluator: 'json-schema', schema: 'https://schema.org/...'
};
```

Unlike assertions I do think having `evaluatior` (bikeshed) be a shorthand is fine since it defines what is being parameterized and I cannot think of a reason to drop it ever even if it is always implicitly defined.

**Comment by lucacasonato** [comment]
Not relevant to the refocused scope of this proposal. Please move any concerns about the import attributes module bag to that proposal, or the TC39 Discourse.
