### ISSUE TITLE
`export source x from "y"`

### ISSUE THREAD

**Issue by lucacasonato** [tc39/proposal-import-reflection#46]
Should we also add this as a shorthand for:

```js
import source x from "y";
export { x };
```

**Comment by guybedford** [comment]
`export { a } from 'b'` will not create a local `a` binding, instead it is only the external binding name.

Similarly, perhaps an `export source x from 'y'` would do the same thing by default - that is, it is not a shorthand but a new syntax entirely.

We could in theory decide either way though.

**Comment by jridgewell** [comment]
Note that we _still_ don't have `export foo from "foo"` syntax: https://github.com/tc39/proposal-export-default-from

**Comment by ljharb** [comment]
oh true, in that case that proposal would add `export source foo from 'foo'` as part of adding `export foo from 'foo'`.

that underscores, though, the need for that proposal, since `export source { default } from 'foo'` wouldn't be available as a workaround otherwise.

**Comment by lucacasonato** [comment]
We decided during the Module Harmony call to defer this until `export foo from "foo"` is a thing to not create asymmetry.
